---
- name: template bifrost-inventory.json
  template:
    src: bifrost-inventory.json.j2
    dest: "{{ bifrost_inventory_path }}"

# Unsure if I'll really need this, but, for now.
- name: Get enrolled inventory
  shell: >
    ironic node-list
  environment: "{{ bifrost_env }}"
  register: enrolled_inventory

- name: Start enrollment, enroll everything every time.
  shell: >
    ansible-playbook -i inventory/bifrost_inventory.py enroll-dynamic.yaml
  args:
    chdir: "{{ bifrost_repo_path }}/playbooks"
  environment: "{{ bifrost_env }}"

- name: Set root device for each inventory item, every time.
  shell: >
    ironic node-update {{ item.uuid }} add properties/root_device='{"{{ item.root_device_type }}": "{{ item.root_device }}"}'
  with_items: "{{ bifrost_inventory }}"
  environment: "{{ bifrost_env }}"
  when: item.root_device_type is defined and item.root_device is defined
