---
# Steps primarily learned from:
# http://docs.openstack.org/developer/bifrost/readme.html
# ...up to the end of the "installation" section.

- name: Enable EPEL
  package:
    name: epel-release
    state: present

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - mlocate
    - ntp

- name: Update time with ntp
  command: ntpdate pool.ntp.org

- name: Start and enable NTP daemon
  systemd:
    name: ntpd
    state: started
    enabled: true

- name: Disable selinux
  selinux:
    state: disabled

- name: Generate an SSH key for root
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Wipe bifrost clone
  file:
    path: /usr/src/bifrost
    state: absent

- name: Clone bifrost
  git:
    repo: https://git.openstack.org/openstack/bifrost.git
    dest: /usr/src/bifrost
    version: "{{ bifrost_version }}"

- name: Template group vars
  template:
    src: "group_vars.{{ item }}.j2"
    dest: "/usr/src/bifrost/playbooks/inventory/group_vars/{{ item }}"
  with_items:
    - baremetal
    - localhost
    - target

- name: Export VENV path for virtual environment setup
  shell: >
    export VENV=/opt/stack/bifrost

- name: Run the env setup script
  shell: >
    bash /usr/src/bifrost/scripts/env-setup.sh
  args:
    creates: /etc/.bifrost-env-setup

- name: Mark env setup complete
  file:
    path: /etc/.bifrost-env-setup
    state: directory

- name: Annnnd! We run the installation playbook.
  shell: >
    /root/.local/bin/ansible-playbook \
      -e enable_venv=true \
      -i inventory/target \
      install.yaml
  args:
    chdir: /usr/src/bifrost/playbooks
    creates: /etc/.bifrost-installed

- name: Mark bifrost install complete
  file:
    path: /etc/.bifrost-installed
    state: directory
