---
# Steps primarily learned from:
# http://docs.openstack.org/developer/bifrost/readme.html
# ...up to the end of the "installation" section.

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - mlocate
    - ntp
    - epel-release

# grrrr at lack of cache update
- name: Install Python and Ansible
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python
    - python-devel
    - python-pip
    - ansible

- name: Check if NTP daemon is running
  command: systemctl status ntpd
  ignore_errors: true
  changed_when: false
  register: service_ntpd_status

- name: Update time with ntp
  command: ntpdate pool.ntp.org
  ignore_errors: true
  when: service_ntpd_status | failed

- name: Start and enable NTP daemon
  systemd:
    name: ntpd
    state: started
    enabled: true

- name: Disable SElinux
  selinux:
    state: disabled

- name: Wipe bifrost clone
  file:
    path: "{{ bifrost_repo_path }}"
    state: absent

- name: Clone bifrost
  git:
    repo: "{{ bifrost_repo }}"
    dest: "{{ bifrost_repo_path }}"
    version: "{{ bifrost_version }}"

- name: Template group vars
  template:
    src: "group_vars.{{ item }}.j2"
    dest: "{{ bifrost_repo_path }}/playbooks/inventory/group_vars/{{ item }}"
  with_items:
    - baremetal
    - localhost
    - target

# TODO: this should be removed after this is merged: https://review.openstack.org/#/c/471750
- name: Upgrade setuptools with pip
  pip:
    name: setuptools
    extra_args: --upgrade

- name: Annnnd! We run the installation playbook.
  shell: >
    ansible-playbook -i inventory/target install.yaml
  args:
    chdir: "{{ bifrost_repo_path }}/playbooks"
    creates: "{{ bifrost_repo_path }}/.bifrost-installed"
  tags:
    - remote_deploy

- name: Mark bifrost install complete
  file:
    path: "{{ bifrost_repo_path }}/.bifrost-installed"
    state: directory
