---
# A suite of things to do after bifrost is installed.
# ...such as configuring ironic.

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Make sure the ironic logs directory exists
  file:
    path: /var/log/ironic
    owner: ironic
    group: ironic
    state: directory

- name: Ensure ironic services running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - ironic-api
    - ironic-conductor
    - ironic-inspector
